---

dist: xenial

language: python

env:
  matrix:
    - MOLECULE_SCENARIO_NAME="centos-7"
    - MOLECULE_SCENARIO_NAME="suse-15"
    - MOLECULE_SCENARIO_NAME="ubuntu-16.04"
    - MOLECULE_SCENARIO_NAME="ubuntu-18.04"

matrix:
  allow_failures:
    - env: MOLECULE_SCENARIO_NAME="centos-7"
    - env: MOLECULE_SCENARIO_NAME="suse-15"

before_install:
  - |
    sudo apt-get -y purge lxc-* lxd-* && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get install -y snapd
    sudo snap refresh && sudo snap install lxd
    sudo lxd init --preseed < .travis.lxd.yml

  - |
    sudo apt-get -y purge python-openssl && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get -y install curl gcc libffi-dev libssl-dev make python python-dev
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python
    sudo -H pip install --upgrade --requirement requirements.txt

install:
  - |
    git submodule init
    git submodule sync
    git submodule update

script:
  - travis_wait 120 sudo ./scripts/run-tests.sh molecule test -s $MOLECULE_SCENARIO_NAME
