---

dist: xenial

language: minimal

services: docker

env:
  matrix:
    - DOCKER_IMAGE: 'ubuntu:16.04'
    - DOCKER_IMAGE: 'ubuntu:18.04'
    - DOCKER_IMAGE: 'centos/systemd:latest'

before_install:
  - docker version
  - docker info

install:
  - sudo -H ./scripts/bootstrap-ansible.sh

script:
  - sudo -H ./scripts/run-tests.sh
