---

ceph_fsid: "{{ groups['ceph-mon'][0] | to_uuid }}"
ceph_mon_initial_members: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ host }},
  {%- endfor -%}
ceph_mon_host: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ hostvars[host]['ansible_default_ipv4']['address'] }},
  {%- endfor -%}
