---

# ceph-common
ceph_fsid: "{{ hostvars[groups['ceph-mon'][0]].ansible_machine_id | to_uuid }}"
ceph_mon_initial_members: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ host }},
  {%- endfor -%}
ceph_mon_host: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ hostvars[host].ansible_eth1.ipv4.address }},
  {%- endfor -%}
ceph_public_network: "{{ (ansible_eth1.ipv4.network + '/' + ansible_eth1.ipv4.netmask) | ipaddr('net') }}"
ceph_cluster_network: "{{ (ansible_eth1.ipv4.network + '/' + ansible_eth1.ipv4.netmask) | ipaddr('net') }}"

# etcd
etcd_cert_file: "/etc/kubernetes/pki/etcd/server.crt"
etcd_key_file: "/etc/kubernetes/pki/etcd/server.key"
etcd_trusted_ca_file: "/etc/kubernetes/pki/etcd/ca.crt"
etcd_peer_cert_file: "/etc/kubernetes/pki/etcd/peer.crt"
etcd_peer_key_file: "/etc/kubernetes/pki/etcd/peer.key"
etcd_peer_trusted_ca_file: "/etc/kubernetes/pki/etcd/ca.crt"
etcd_listen_peer_urls: "https://{{ ansible_eth1.ipv4.address }}:2380,https://127.0.0.1:2380"
etcd_listen_client_urls: "https://{{ ansible_eth1.ipv4.address }}:2379,https://127.0.0.1:2379"
etcd_initial_advertise_peer_urls: "https://{{ ansible_eth1.ipv4.address }}:2380"
etcd_initial_cluster: >-
  {%- for host in ansible_play_hosts -%}
  {{ host }}=https://{{ hostvars[host].ansible_eth1.ipv4.address }}:2380,
  {%- endfor -%}
etcd_advertise_client_urls: "https://{{ ansible_eth1.ipv4.address }}:2379"
etcd_csr_subject_alt_name: >-
  {%- for host in ansible_play_hosts -%}
  DNS:{{ host }},
  {%- endfor -%}
  DNS:localhost,
  {%- for host in ansible_play_hosts -%}
  IP:{{ hostvars[host].ansible_eth1.ipv4.address }},
  {%- endfor -%}
  IP:127.0.0.1
etcd_peer_csr_subject_alt_name: >-
  {%- for host in ansible_play_hosts -%}
  DNS:{{ host }},
  {%- endfor -%}
  DNS:localhost,
  {%- for host in ansible_play_hosts -%}
  IP:{{ hostvars[host].ansible_eth1.ipv4.address }},
  {%- endfor -%}
  IP:127.0.0.1

# kubernetes
kubernetes_cluster_name: "{{ hostvars[groups['kube-master'][0]].ansible_machine_id | to_uuid }}"
kubernetes_etcd_external_endpoints: >-
  {%- for host in ansible_play_hosts -%}
  https://{{ hostvars[host].ansible_eth1.ipv4.address }}:2379,
  {%- endfor -%}
kubelet_node_ip: "{{ ansible_eth1.ipv4.address }}"
kube_apiserver_advertise_address: "{{ ansible_eth1.ipv4.address }}"
kube_apiserver_csr_subject_alt_name: >-
  {%- for host in ansible_play_hosts -%}
  DNS:{{ host }},
  {%- endfor -%}
  DNS:localhost,
  {%- for host in ansible_play_hosts -%}
  IP:{{ hostvars[host].ansible_eth1.ipv4.address }},
  {%- endfor -%}
  IP:127.0.0.1

# kubernetes-cephfs-provisioner
cephfs_provisioner_monitors: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ hostvars[host].ansible_eth1.ipv4.address }}:6789,
  {%- endfor -%}

# kubernetes-rbd-provisioner
rbd_provisioner_monitors: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ hostvars[host].ansible_eth1.ipv4.address }}:6789,
  {%- endfor -%}

# kubernetes-csi-cephfs
csi_cephfs_monitors: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ hostvars[host].ansible_eth1.ipv4.address }}:6789,
  {%- endfor -%}

# kubernetes-csi-rbd
csi_rbd_monitors: >-
  {%- for host in groups['ceph-mon'] -%}
  {{ hostvars[host].ansible_eth1.ipv4.address }}:6789,
  {%- endfor -%}
